linear_regression:
  model_type: linear
  alpha: 1.0
  fit_intercept: true

arima:
  model_type: arima
  p: 1
  d: 1
  q: 1

sarima:
  model_type: sarimax
  p: 1
  d: 1
  q: 1
  P: 1
  D: 1
  Q: 1
  m: 12
  exog: true
