linear_regression:
  model_type: linear
  alpha: 1.0
  fit_intercept: true

arima:
  model_type: arima
  p: 1
  d: 1
  q: 1
  fit_options:
    method: "lbfgs"
    maxiter: 200

sarima:
  model_type: sarimax
  p: 1
  d: 1
  q: 1
  P: 1
  D: 1
  Q: 1
  m: 12
  training_days: 365
  exog: true
  fit_options:
    method: "lbfgs"
    maxiter: 300
    disp: false
    ftol: 1e-6
    gtol: 1e-6
